name: Update Malaimurasu PDF Daily

on:
  schedule:
    - cron: '30 2 * * *'  # Run at 8 AM IST daily
  workflow_dispatch:

jobs:
  update_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Script
      run: python main.py

    - name: Commit and Push PDF
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add malaimurasu.pdf log.txt
        git commit -m "Update Malaimurasu PDF" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
